project:
  type: website
  preview:
    port: 4200

website:
  title: "Meditations"
  description: Observations of a Pragmatic Philosopher
  favicon: pfp.png
  repo-url: https://github.com/0xAurelius/meditations
  open-graph:
    site-name: Meditations | Marcus Aurelius
  navbar:
    right:
      - text: Journal
        href: blog.qmd
      - speaking.qmd
      - icon: github
        href: https://github.com/0xAurelius
      - icon: twitter
        href: https://twitter.com/0xKlimaurelius
      - icon: envelope
        href: mailto:marcus_aurelius_0x@proton.me
format:
  html:
    theme:
      light: pulse
      dark: vapor
    css: styles.css

execute:
  freeze: auto
