project:
  type: website

website:
  title: "Meditations"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/0xAurelius
      - icon: twitter
        href: https://twitter.com/0xKlimaurelius
format:
  html:
    theme: pulse
    css: styles.css

execute:
  freeze: auto
